// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1E6etJELnyJSXEaVmbw2_KuWEj93jODM',
    appId: '1:187949127471:web:ce03b749d6e1fdf87573da',
    messagingSenderId: '187949127471',
    projectId: 'bizbora',
    authDomain: 'bizbora.firebaseapp.com',
    storageBucket: 'bizbora.appspot.com',
    measurementId: 'G-1YFG7R4NWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhTHQWVOi8E1mNEw6DEUSTaXwg23_uN-g',
    appId: '1:187949127471:android:77b20a38e260ea1d7573da',
    messagingSenderId: '187949127471',
    projectId: 'bizbora',
    storageBucket: 'bizbora.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBssytHCWpx1cwZsThUPUsBnptzPJ3qYG0',
    appId: '1:187949127471:ios:c8526fceac7a83797573da',
    messagingSenderId: '187949127471',
    projectId: 'bizbora',
    storageBucket: 'bizbora.appspot.com',
    iosClientId: '187949127471-8sbuij4mh79vtukntdv65l36gbohtpgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizbora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBssytHCWpx1cwZsThUPUsBnptzPJ3qYG0',
    appId: '1:187949127471:ios:2faf864d5d66901c7573da',
    messagingSenderId: '187949127471',
    projectId: 'bizbora',
    storageBucket: 'bizbora.appspot.com',
    iosClientId: '187949127471-k1rklhutqiasufh0l4695htne6j7uov6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizbora.RunnerTests',
  );
}
